---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2019-05-07 at 3-12-36 AM1/Screen Shot 2019-05-07 at
      3-12-36 AM1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/Screen%20Shot%202019-05-07%20at%203-12-36%20AM1/Screen%20Shot%202019-05-07%20at%203-12-36%20AM1.png"
