---
version: 2
multicolumn: false
web-width: 1000px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/omics_expression_by_location/omics_expression_by_location.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/omics_expression_by_location/omics_expression_by_location.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/omics_expression_by_location"
