---
version: 2
multicolumn: false
web-width: 1000px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/health_status_differential_network/health_status_differential_network.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/health_status_differential_network/health_status_differential_network.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/health_status_differential_network"
