---
version: 2
multicolumn: false
web-width: 1000px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Partial_network_Combined/Partial_network_Combined-min.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/260401/articles/362072/master/folder/figures/Partial_network_Combined"
    url: "/users/260401/articles/362072/master/file/figures/Partial_network_Combined/Partial_network_Combined-min.png"
