---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Xmetab Yall/Xmetab Yall.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/Xmetab%20Yall/Xmetab%20Yall.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/Xmetab Yall"
