---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/pls results/pls results.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/pls%20results/pls%20results.xlsx"
