---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/peaks_to_paths_0_dpi600edit/peaks_to_paths_0_dpi600edit.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/peaks_to_paths_0_dpi600edit/peaks_to_paths_0_dpi600edit.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/peaks_to_paths_0_dpi600edit"
