---
version: 2
multicolumn: false
web-width: 150px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2019-05-06 at 6-27-41 PM/Screen Shot 2019-05-06 at 6-27-41
      PM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/Screen%20Shot%202019-05-06%20at%206-27-41%20PM/Screen%20Shot%202019-05-06%20at%206-27-41%20PM.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/Screen Shot 2019-05-06
      at 6-27-41 PM"
